# Generated by Django 4.2.1 on 2023-05-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_contact_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.city', verbose_name='Город')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.contact', verbose_name='Контакты')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.workingday', verbose_name='Рабочие дни')),
                ('working_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.workingtime', verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'ordering': ['update_time'],
            },
        ),
    ]
