# Generated by Django 4.2.1 on 2023-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_establishment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Рабочие день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterModelOptions(
            name='workingtime',
            options={'verbose_name': 'Рабочая время', 'verbose_name_plural': 'Рабочие время'},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
