# Generated by Django 4.2.1 on 2023-05-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_type_options_alter_workingday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'ordering': ['update_time'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведении'},
        ),
    ]
